server {
    listen 80;
    server_name mahavirautomation.cloud www.mahavirautomation.cloud;

    location / {
        root /var/www/mahavirautomation/front-end/dist;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name api.mahavirautomation.cloud;

    # Allow large file uploads (up to 50MB)
    client_max_body_size 50M;

    location / {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}
